#----------------------
# To be changed
#----------------------
BIN = Singleton

SOURCE := \
	Singleton.cpp \
	Singleton.h \
	main.cpp

#----------------------
# Do not change
#----------------------
CC = g++

all: $(BIN)

$(BIN): $(SOURCE)
	$(CC) $(SOURCE) -o $(BIN)

clean:
	rm -f $(BIN)

#----------------------
