#----------------------
# To be changed
#----------------------
BIN = BinarySearchTree

SOURCE := \
	$(BIN).cpp

#----------------------
# Do not change
#----------------------
CC = g++

all: $(BIN)

$(BIN): $(SOURCE)
	$(CC) $(SOURCE) -o $(BIN)

clean:
	rm -f $(BIN)

#----------------------
